version: '3.8'

services:
  backend:
    image: negative12/rirs-backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
  
  frontend:
    image: negative12/rirs-frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
